I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/startPy.rpy", line 3, in script
    init 0 python:
  File "game/startPy.rpy", line 15, in <module>
    current["name"] = Race(current["name"],current["ears"],current["skinType"],current["skinColour"])
NameError: name 'Race' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/startPy.rpy", line 3, in script
    init 0 python:
  File "F:\renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/startPy.rpy", line 15, in <module>
    current["name"] = Race(current["name"],current["ears"],current["skinType"],current["skinColour"])
NameError: name 'Race' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
pastrymod2 1.0
Thu Jun 11 15:12:40 2020
